### ISSUE TITLE
Error in svconnector_feed regarding use of absolute paths 

### ISSUE THREAD

**Issue by bendoo** [cobwebch/svconnector#10]
I noticed a change in svconnector_feed-extension which broke my set-up.

I always used this config:
$absolutePath='/www/436590_70794/rp-hosting/5150001/6150001/upload/xml/products/';

// Add the external information to the ctrl section
$GLOBALS['TCA']['tx_legamaster_domain_model_legamaster']['ctrl']['external'] = array();
$GLOBALS['TCA']['tx_legamaster_domain_model_legamaster']['ctrl']['external']['tr_en'] = array(
'connector' => 'feed',
'parameters' => array(
'uri' => $absolutePath.'vc_en.xml'
),
'data' => 'xml',
....

But it seems that the latest version can't read correctly the absolute path anymore.
If I change the path to:
$absolutePath='fileadmin/legamaster/xml/';
...this config works fine.

I did a temporary fix by symlinking fileadmin/legamaster/xml/ to the absolute path but I would prefer to put the path directly.

**Comment by fsuter** [comment]
I know what the problem is. The new FileUtility class now calls upon GeneralUtility::getFileAbsFileName() for local paths, even absolute ones. This means that all paths must be within the TYPO3 root path. There used to be a global configuration setting for adding allowed paths, but it doesn't exist anymore. I guess this is related to the introduction of FAL. If you have some directory outside the root path which you want to access, you should define a File Storage pointing to it.

Is that an option for you?

I could implement a workaround allowing for any file paths, but I feel that this would degrade security.

What I propose however is to update the documentation to indicated that absolute paths can be used provided they point to within the TYPO3 root path.

**Comment by bendoo** [comment]
For now, I resolved the issue with a symlink which works just fine. If I can also solve it with defining a File Storage point, this is also ok for me. So just updating the documentation is ok for me pointing out these 2 options.

**Comment by fsuter** [comment]
That was my fault after all ;-)

With a proper usage of the TYPO3 API, the problem is fixed.

**Comment by fsuter** [comment]
That still required a slight change of documentation to be more explicit.

Now I need to update all other connectors which copy that part of the documentation :-(
