### ISSUE TITLE
Release version 3.4.0

### ISSUE THREAD

**Issue by hertach** [cobwebch/svconnector#22]
Hi
First of all thank you for your great extension!
In your svconnector_sql, svconnector_json and svconnector_feed extensions, you have a dependency on the svconnector version 3.4.0. The current version is 3.3.1, which would already be ready for TYPO3 V10. When does version 3.4.0 come?
Best regards

**Comment by fsuter** [comment]
Hi. Well, it's a bit hard to say. This dependency is there when you use the current master version. I suppose you are using it because you need v10 compat?
I was wanting to wait until External Import is also compatible with v10 and release everything, but your comment makes me realize that this is taking way too long (I have trouble with v10 compat in the External Import backend modules) and that I should release the connector services without waiting for the rest.
So I'll try to make a release today or tomorrow.

**Comment by hertach** [comment]
Hi,
yes, we want to upgrade to V10 (with the help of Composer) and we have some extensions that have dependencies.
Thank you for your quick reply and for your great work.
