### ISSUE TITLE
Question: POST method to import

### ISSUE THREAD

**Issue by cyril392** [cobwebch/svconnector#29]
Hello,
I use the extension to import data from a JSON feed. I use the latest versions of the extensions for a TYPO3 V11. The public API I use necessarily returns data via POST methods and not GET. I have the impression that the extension uses the GET method to retrieve the data (which would be logical) because when importing I get the error I get on postman when I make a GET request. Is it possible to use the extension to pass a parameter to specify a POST request rather than a GET request?
Thanks in advance!

**Comment by fsuter** [comment]
Hi, you're right that the use of "GET" is hard-coded. It's in class `\Cobweb\Svconnector\Utility\FileUtility` on line 101. It would be definitely interesting to make this configurable, but I don't have the time to do this right now. Hopefully you can patch the aforementioned class yourself.

And I'll keep this ticket open (and move it to the "svconnector" extension) so that I can add the feature at a later point.

**Comment by fsuter** [comment]
This is now possible in the `FileUtility`class. It still needs to be implemented by the various connectors.

Also, I suspect that this is just a first step: enabling POST requests will probably very soon lead to the need for defining a request body, rather than just query parameters, but let's proceed with that already.
