### ISSUE TITLE
Missing tags for old versions

### ISSUE THREAD

**Issue by vertexvaar** [cobwebch/svconnector#3]
I am required to install an older version of this extension, but composer did not find any version other than 3.x so i had a look and found out the repo is missing all tags below 3.x
This would force me to require commits rather than version, which is not an intended usage of composer and might break in composer in the future. 
Please add tags to the older releases (at least down to 2.4 if possible). Thanks!

**Comment by fsuter** [comment]
I tried to do this, but the issue is that there were no composer.json files in these old releases, so Packagist does not see that old release. As far as I understand, you should be able to use composer.typo3.org for such old releases.

I'm not really willing to go through the hassle of adding a composer.json to an old branch, especially since would need to be done also for the specific svconnector_* services.

Can you try with composer.typo3.org and see if you can live with that?

**Comment by vertexvaar** [comment]
Things have changed quite fast so the requirement became obsolete.
For anyone else the composer.typo3.org solution should be viable.
Thank you for your support!
